bitmovin/bitmovin-player-ui

CHANGELOG.md
src/ts/components/settingspanel.ts

Uses mouseleave event to not close when option list are open.
The main difference is that if an option list is open,
it won't close even if the mouse leaves the menu area.

Makes the menu closign more intuitive

---

CHANGELOG.md
src/ts/components/uicontainer.ts

So it pretty much bypass all the logic in `configureUIShowHide` and just fires a `onControlsShow` event as soon as the ui is configured (otherwise component are not subscribed).

Adds the option to alway show the controls

---

CHANGELOG.md
src/ts/components/seekbarlabel.ts
src/ts/components/tvnoisecanvas.ts
src/ts/dom.ts
src/ts/imageloader.ts

The thumbnail size was set programmatically in pixels and was directly taken from the sprites file, so it could only be changed by adjusting the sprites file. 
Now the thumbnail size can be a relative or absolute size. It's not programmatically set any more so it can be set in CSS too.

Set thumbnail size from CSS

---

CHANGELOG.md
src/ts/uimanager.ts

Add `UIConfig#container` config property to specify a custom place in the DOM where the UI will be put into. Can be used to place it somewhere else beside the default player figure.

Custom UI container

---

CHANGELOG.md
src/ts/components/container.ts
src/ts/components/subtitleoverlay.ts

`Container#removeComponents` did not reliably remove all components if the container contained multiple components. The list of components was iterated and modified at the same time, leading to skipped components that were not removed. 
This issue became noticeable on the subtitle overlay when multiple subtitle cues were displayed at the same time but not all got cleared on a seek.
The fix is to iterate a copy of the components list while modifying the original list.

Fix Container#removeComponents

---

CHANGELOG.md
src/ts/components/container.ts

Only add new components and remove removed components, leaving remaining components alone. This avoids that their innerHTML is lost to garbage collection in IE11, which let to empty subtitle labels.

Fix Container#updateComponents by only processing changes (fixes subtitles in IE11)

---

src/ts/components/subtitleselectbox.ts

An empty subtitle select box would not be displayed when the first subtitle was added dynamically, because the "off" option would be missing and select boxes are only displyed when at least two options are available ("off" +  one actual option).
This changes the logic to also add the "off" option when the first subtitle is added.

Fix dynamic adding of first subtitle

---

CHANGELOG.md
src/ts/components/subtitleoverlay.ts

It can happen that two subtitle cues are to be rendered with the same text at the same time, leading to colliding IDs that are used in the internal lookup table. The second cue would override the first one in the lookup table, cutting the reference to the first one, so it never got removed again (except on a clear).
This PR adds support for colliding IDs by maintaining a list of cues for each ID instead of just one associated item.

Support multiple subtitle cues with same ID

---

src/ts/components/adclickoverlay.ts
src/ts/components/hugeplaybacktogglebutton.ts
src/ts/components/hugereplaybutton.ts
src/ts/components/playbacktimelabel.ts
src/ts/components/playbacktogglebutton.ts
src/ts/components/seekbar.ts
src/ts/components/volumeslider.ts
src/ts/components/volumetogglebutton.ts
src/ts/player-events.d.ts
src/ts/player.d.ts

There is an open Pull Request at the player which enables issuer parameters for a multitude of evens:
- mute
- unmute
- volumeChange
- seek
- timeshift
This PR makes use of these new parameters.

Using the new issuer parameter in Events

---

CHANGELOG.md
src/ts/uimanager.ts

Fires a `ON_READY` event into the UI when the UI is loaded after the player is ready and will thus not receive an `ON_READY` from the player. This is done because some components wait for `ON_READY` to initialize their state.

Fix init components on ready v2

---

gulpfile.js

Moves the JS output filename to the ``paths` config object and exports the object so it can be customized from other gulpfiles that import and reuse this project's gulpfile. Helpful for packages use this package as their base and modify the framework to create a custom build.

Improve Gulpfile reuse

---

CHANGELOG.md
src/ts/components/audioqualityselectbox.ts
src/ts/components/videoqualityselectbox.ts
src/ts/player-events.d.ts
src/ts/player.d.ts

UI `AudioQualitySelectBox` and `VideoQualitySelectBox` selected items are now correctly kept in sync with API calls to `setAudioQuality`/`setVideoQuality`.

Implement new quality selection API for player 7.3.1

---

CHANGELOG.md
src/ts/components/audiotrackselectbox.ts

Select the correct audio track after updating the items in `AudioTrackSelectBox`. Before, when the select box was updated, no item was selected, but it looked like the first one was selected since browers automatically show it as the active item.
Now we query the player for the active track and set it correctly.

Fix audio track selection

---

CHANGELOG.md
src/html/index.html
src/scss/skin-modern/components/_subtitleoverlay-cea608.scss
src/scss/skin-modern/components/_subtitleoverlay.scss
src/ts/components/subtitleoverlay.ts

The basic issue was that under certain aspect ratios texts were overlapping. See issue #61 for a description and before/after comparison.
This PR
* Rewrites the layouting code
* Greatly simplifies the CSS
* Removes all hardcoded values except the ones that are really "hardcoded", which is only the 32x15 grid size
* Improves code readability by adding comments and renaming variables
* Calculates and applies the font size only when CEA cues are active

CEA-608: Rewritten text layouting, CSS simplification & code improvements

---

CHANGELOG.md
src/scss/skin-modern/components/_subtitleoverlay-cea608.scss
src/ts/components/subtitleoverlay.ts

#66 added a `white-space: nowrap` CSS rule to avoid unwanted line breaks when a caption would touch the right border of the subtitle area. This probably happened due to floating values used for sizes and positioning and when captions contained a whitespace they became a little bit wider than expected, leading to line breaks. The CSS rule avoided that.
Unfortunately, Safari does not output CEA-608 caption lines separately, but as a single string without line breaks. This is probably because Safari converts the captions to WebVTT, which is inherently designed for multiline captions because it is built on the concept of layout boxes with a position and width that leads to a specific height. At least that is my interpretation of the data from Safari's `VTTCue` combined with how Safari's …

Allow multiline CEA-608 captions

---

CHANGELOG.md
src/ts/components/subtitleoverlay.ts

This PR fixes unnecessary line breaks in Safari (which renders font sizes differently to other browsers) and applies the CEA-608 styling before the texts are added to the DOM, avoiding "style flickering".

Improve CEA-608 rendering

---

CHANGELOG.md
src/ts/components/seekbar.ts

The smooth playback position update timer continued to run after playback has finished, unnecessarily using resources.
This PR changes the behavior to stop the updater once the end of playback is reached.

Stop SeekBar smooth position update on playback finished

---

CHANGELOG.md
src/ts/components/seekbar.ts

When pausing a live stream with a DVR window, the playback position stays still and thus moves away from the live edge. The visual playback position indicator on the seekbar should therefore move towards the back.
Because this case was not handled, the playback position during a paused live stream with timeshift window only updated "accidentally" for a few seconds while the buffer was filled, but the buffer is usually < 1 minute while the timeshift window can be much longer (e.g. multiple hours).
This PR adds a timer that is activated once a live stream with timeshift window is paused, and deactivated once playback continues. It updates the playback position once per second.

Update playback position during paused live streams with DVR window

---

CHANGELOG.md
src/ts/components/playbacktimelabel.ts

As pointed out in https://github.com/bitmovin/bitmovin-player-ui/pull/76#pullrequestreview-84722035, the live edge indicator continued to indicate the player being at the live edge (red dot) while playback was paused and the playhead shifted behind the live edge.
This PR switches off the live indicator when a live stream is paused and the playhead is away from the live edge.

Turn off live edge indicator during pause

---

CHANGELOG.md
src/scss/skin-modern/components/_seekbar.scss

Due to style changes in #79, `SeekBar` markers were not rendered correctly any longer. This PR fixes the marker style to get them rendered correctly again.

Fix SeekBar marker style

---

CHANGELOG.md
src/ts/components/volumeslider.ts

The volumeslider would try setting the volume on the player to see if it actually changes to detect if we are on a device which does not support setting of volume.
When the player was in muted autoplay and unmuted autoplay was disallowed by the browser this lead to a pause on the video element. The play call afterwards sometimes did not do anything as the player might still have been in playing state (it seems the video element does not fire the pause event immediately).
To avoid this strange behaviour i changed the code to probe a dummy video element with a minimal audio source.

Rework volume changeability detection

---

CHANGELOG.md
src/ts/components/seekbar.ts

The bar indicators of `SeekBar` and `VolumeSlider` use the `transform: scaleX(value)` CSS rule to scale their width horizontally (or `scaleY` vertically). When the value is exactly `1`, browers seem to render the elements differently and their height is slightly different. Two overlaying bars where one has a scale of `1` and the other `!=1` do not match in height/width, leading to an unpleasant rendered result as visible here:
When one bar jitters around a value of `1`, as it frequently can happen with the buffer indicator bar, this leads to an even worse flickering effect.
I have tried lots of different ways of applying CSS rules and building the DOM tree to avoid this rendering issue but could not find a way to avoid it. I also wasn't able to find any related issues of other people on …

Fix flickering bar indicators of SeekBar & VolumeSlider

---

CHANGELOG.md
src/ts/eventdispatcher.ts

In `EventDispatcher`, when an event listener with array index `y <= x` is unsubscribed from within the event handler with index `x`, then the event handler `x+1` is not called because it shifts back to index `x`. To fix this, the `dispatch` method now iterates over a copy of the list of event listeners to avoid the "concurrent" modification of the iterated list. `Array.slice(0)` is used to create a copy of the array which, according to benchmarks, is the most effective way to copy an array.

Fix concurrent event listener array modification in EventDispatcher

---

CHANGELOG.md
src/ts/playerutils.ts

Depending on when the UI is loaded, it's either the `ON_READY` event (in the `UIContainer`) or the `getState` function that determines the state of the UI. `getState` checked if a source is loaded, which must not necessarily be the case when `isReady` === true, e.g. when a player is setup without a source. The UI state is initialized with `getState` but when an `ON_READY` event arrives afterwards, which happens when the UI is loaded before the player setup is finished, the UI changed into the `PREPARED` state, no matter if a source is loaded or not. If the UI is loaded later, it only changed into the `PREPARED` state if a source is actually loaded. This resulted in an inconsistent behavior, depending on when the UI is loaded. Now it's the `ON_READY` event and `isReady` flag (which are …

Consistent UI prepared-state

---

src/ts/player.d.ts

Added the `getSeekableRange` to the PlayerAPI because it was missing

Add getSeekableRange to the PlayerAPI

---

CHANGELOG.md
src/ts/components/playbackspeedselectbox.ts
src/ts/player-events.d.ts

There was no event in the player to notify about playback speed changes. This event will be introduced in v7.7. The UI now listens to the event (if the player version supports it) and changes the selector accordingly.

Use ON_PLAYBACK_SPEED_CHANGED event

---

CHANGELOG.md
src/ts/player.d.ts
src/ts/uimanager.ts

Since Player Version 7.7 add/removeEventHandler are deprecated. This PR introduces the adaptation to the new on + off methods while keeping a fallback to the old functionality to stay compatible with older versions

Use on/off instead of addEventHandler/removeEventHandler when available

---

CHANGELOG.md
src/ts/components/hugeplaybacktogglebutton.ts
src/ts/player-events.d.ts

When a play call was tried but blocked due to disabled autoplay on some devices the `play` event would be fired, but the player would never transition into playing. This breaks the hugeplaybacktogglebutton as it only waits for the first `play` event to start the the waiting for a potential double click for potential fullscreen handling. This handling destroys the user interaction needed for the play call to succeed.
As a fix we now reset this first play flag on an `onWarning` event to use the first click as a user interaction to call play.

fix blocked autoplay

---

CHANGELOG.md
src/scss/skin-legacy/components/_seekbar.scss
src/scss/skin-modern/components/_seekbar.scss
src/ts/components/seekbar.ts

Missing `-webkit` prefixes on `transform` properties led to a dysfunctional `SeekBar` in Android 4.4's `WebView` (which is based on an old `WebKit` engine).

Fix seekbar in Android 4.4 WebView

---

src/ts/uimanager.ts

Implements #101 and provides multiple ways to switch between UI variants via the public `UIManager` API:
```ts
interface UIConfig {
/** 
* A configuration flag that allows to turn off automatic UI variant switching to allow purely 
* externally triggered switching through `resolveUiVariant` and/or directly through 
* `switchToUiVariant` (default `true`)
*/
autoUiVariantResolve?: boolean;
}
class UIManager {
/**
* An event that is triggered just before the next UI variant is resoved and the UI variant 
* is switched. It is fired when the switch is triggered from an automatic switch and when 
* calling `resolveUiVariant` and can be used to modify the `UIConditionContext` before 
* the UI variant is resoved.
*/
onUiVariantResolve: EventDispatcher<UIManager, UIConditionContext>;
/*
* Returns …
```

Add API to switch UI variants

---

CHANGELOG.md
src/scss/skin-legacy/components/_hugeplaybacktogglebutton.scss
src/scss/skin-modern/components/_hugeplaybacktogglebutton.scss
src/ts/components/hugeplaybacktogglebutton.ts

Implements #107
This does not work in all cases because it depends on when the UI is initialized and which events from the player it receives. It works in some cases though, so it's an improvement for some users.

Animate HugePlaybackToggleButton only on state changes

---

CHANGELOG.md
src/ts/components/settingspanel.ts

When a select box was hovered, but the mouse pointer went outside the screen (without clicking to release the hover selection), select boxes of the `SettingsPanel` would not get hidden with the rest of the panel, but rather floated around without a visible parent. In IE11 the items itself would then even hide when they were hovered again which made things even worse.
When hiding the `SettingsPanel` set the visibility to `none` for a very short time to remove the elements active/hovered state

Hide hovered select boxes

---

CHANGELOG.md
src/ts/components/listselector.ts

Adds `ListSelectorConfig.filter` and `ListSelectorConfig.translator` to allow filtering items and translating labels of items added through `ListSelector.addItem`. 
While this does not seem to make a lot of sense in situations where the programmer has control over what is added via `addItem`, it is very useful for subclasses that automatically populate themselves (`SubtitleSelectBox`, `AudioTrackSelectBox`, ...), where no control over the added items was possible until now:
```ts
new SubtitleSelectBox({
// Filter out all French subtitles (sorry my French friends, we still like you!)
filter: (listItem) => listItem.key !== 'fr' && !listItem.label.includes('Fran'),
// Translate the Spanish label but no other
translator: (listItem) => {
if (listItem.key === 'es') {
return 'Aiaiai!';
}
return …
```

Add filter & translator functions to ListSelector

---

CHANGELOG.md
src/ts/components/settingspanel.ts

The fix for hiding hovered select boxes: https://github.com/bitmovin/bitmovin-player-ui/pull/116 did not cover the case, that the whole UI is hiding.
We now listen to the `uimanager.onControlsHide` to apply the same functionality on the global hiding of the UI

Hide hovered select boxes when the whole UI hides

---

CHANGELOG.md
src/ts/components/seekbarlabel.ts
src/ts/dom.ts

We did always expect x/y/w/h values for a thumbnail. With single images those properties don't have to be present.
An example file looks like this:
```
WEBVTT
00:00:00.0 --> 00:00:06.142
http://example.com/images/1.jpg
00:00:06.142 --> 00:00:12.285
http://example.com/images/2.jpg
```
This PR creates the CSS properties accordingly for the single image.

Single image thumbnails

---

CHANGELOG.md
src/ts/storageutils.ts

Newer Firefox versions throw a DOMException when accessing the localStorage object. Before, they only threw the exception when the object was used. Detection code has been updated according to the updated code on MDN.

Update localStorage detection code

---

src/ts/components/hugeplaybacktogglebutton.ts
src/ts/components/playbacktogglebutton.ts

In player v8 the API method `isPlaying` would only return `true` once the media element has started playback. In previous versions it would already return `true` once the play was initiated (i.e. `player.play` was called). 
For player v8 we need to track the state of a play being initiated separately so the play buttons can react to that. I am using the `onPlay` event for that matter.

Track initiated play for player v8

---

CHANGELOG.md
src/ts/components/uicontainer.ts
src/ts/uimanager.ts

Until now it was only possible to configure if the UI controls will be hidden after a certain amount of inactivity time (`UIContainerConfig.hideDelay`) or if they are always shown.
This PR adds `UIContainerConfig.hidePlayerStateExceptions` that allows to specify a list of player states in which the UI controls will always be shown, e.g.
https://github.com/bitmovin/bitmovin-player-ui/blob/b2e1f004086d12c6137bd8c0d3edfb56109d118a/src/ts/uimanager.ts#L776
In the small screen UI we prevent the UI controls from hiding in the replay screen to avoid a required double tap on smartphones to first display the controls and then start playback. By always showing the controls, replay can be started with one tap and buttons like the fullscreen button are always easily available.

Prevent controls from hiding in certain player states

---

src/ts/components/uicontainer.ts
src/ts/player.d.ts
src/ts/uimanager.ts

`player.getFigure` has been removed with V8 along with the actual figure
`player.getContainer` now returns the element which embeds the player, use that one

Adjust to player getFigure removal

---

CHANGELOG.md
src/ts/components/admessagelabel.ts
src/ts/components/adskipbutton.ts

Custom skip-messages are not displayed while an ad is playing.
Use text from playerEvent instead of config
It seems weird to me that there are multiple different texts but only one will be taken. 
Should we update the documentation that the text in the player-config has precedence over the text configured in the UI element?

Custom skip ad message not displayed

---

src/ts/components/bufferingoverlay.ts

We show the buffer overlay between play and playing, but don't hide it when we pause. That means that the sequence `Play` -> `Paused` will lead to buffer overlay staying on the screen for the paused duration, which is not correct.

Also hide the buffer overlay when pausing

---

src/ts/uimanager.ts

Intentionally I was investigating a issue that the video-quality select box value was not updating correctly but I was not able to reproduce it in UI v3 with player v8. 
I found another issue that after an UI variant switch some components were not able to update their state again.
Partly revert of [fd817f](https://github.com/bitmovin/bitmovin-player-ui/commit/fd817fc9eb495237e103aba9c68ad8da462cc7aa)

Fix an issue that many components are not updating the content after an ui variant switch

---

src/html/index.html
src/ts/components/recommendationoverlay.ts
src/ts/player.d.ts
src/ts/uimanager.ts

I recognized that the recommendation-overlay was not shown when playback finished.
* update the UI to use the new AdsAPI
* update ad samples
@Reevn two open questions:
* Is it possible to set `skipMessage` and `adMessage`?
* The `skipAfter` is currently not working with the IMA module?

Recommendation overlay not shown

---

CHANGELOG.md
src/ts/components/seekbar.ts

Analytics could not differentiate between user initiated play/pause calls and play/pause called which were issued due to seeking while the player was playing.
Now the play/pause calls which happen during seeking have a different issuer `ui-seek`

Separate issuer in play/pause during seeking

---

src/ts/uimanager.ts

As discussed this removes the `Factory` from `UIManager`

Remove factory in uimanager

---

src/ts/uimanager.ts

Fix an issue that appears when initializing the uimanager without metadata within the uiconfig.

Fix an issue when metadata is undefined in uiconfig

---

src/scss/skin-modern/_skin.scss

Issue: We found out that the entirety UI was misplaced when no bootstrap is on the side. So we added the default `box-sizing` from bootstrap to all elements within the `ui-container`

Fix misplaced UI

---

CHANGELOG.md
src/ts/uimanager.ts

Player v8.0.0 calls `UIManager.release` from within a `PlayerEvent.Destroy` handler, which, due to its async nature, is executed after the player is already destroyed. `UIManager.release` then attempted to unsubscribe all UI event handlers, which led to uncaught `PlayerAPINotAvailableError`s because the `player.off` method wasn't available any more.
This PR adds a detection if the player is still alive, and only unsubscribes the event handler in that case. If the player is already destroyed, the handlers are already invalid and just thrown away.

Fix UIManager.release with destroyed player

---

CHANGELOG.md
src/ts/components/seekbar.ts

If the player was destroyed (`player.destroy()`) without destroying the UI first (`uimanager.release()`) - like it happens in the UI module of player 8.0.0 - the playback position updater of the `SeekBar` attempted to call `player.getCurrentTime()` and provoked a `PlayerAPINotAvailableError`.
The `player.getCurrentTime()` is now wrapped in a `try/catch` and the position updater is stopped when this error happens (once the player is destroyed, the UI becomes unusable anyway so the updater can safely be stopped).

Fix unhandled error in SeekBar

---

CHANGELOG.md
src/ts/components/hugeplaybacktogglebutton.ts

How to test:
* Press the cast button in the player ui
- The cast device selection should open
* Exit the the cast device selection popup without selecting a device (Press X on the popup)
* Wait until the Player UI fades out
-> UI will never come again (before the fix)

Fix issue that the UI becomes unresponsive when user cancels Cast connection establishment.

---

src/scss/skin-modern/_skin.scss
src/scss/skin-modern/components/_controlbar.scss
src/scss/skin-modern/components/_titlebar.scss

#169 introduced a generic `box-sizing: border-box;` for all elements within the `UIContainer` to fix styling issues that appeared in an environment without Bootstrap or similar frameworks with certain style baseline resets.
Unfortunately this introduces the issue that UI components could not override this setting without `!important` or other complicated selector hacks.
This PR removes the generic `box-sizing` reset and only sets it in the appropriate places where necessary.

Cleanup box-sizing

---

CHANGELOG.md
src/scss/skin-modern/_skin-smallscreen.scss
src/scss/skin-modern/components/_button.scss
src/scss/skin-modern/components/_controlbar.scss
src/scss/skin-modern/components/_settingspanelpagebackbutton.scss
src/scss/skin-modern/components/_settingspanelpageopenbutton.scss
src/scss/skin-modern/components/_watermark.scss
src/scss/skin-modern/components/subtitlesettings/_subtitlesettingsresetbutton.scss

This is extracted from #178 as **part 1**.
We deiced do split #178 into two parts: first will be to just replace margins with paddings to have a slight improvement for the hit boxes. Part two would be to use available space until the edge of the UI.

Replace margins with paddings to improve hit boxes

---

CHANGELOG.md
gulpfile.js
package-lock.json
package.json
src/ts/components/component.ts

Adds the following parameters to `gulp`:
* `--outputnames.globalNamespace`: The name of the *global* on the `window` object to which the UI is attached if loaded without a module loader. Default: `bitmovin.playerui`
* `--outputnames.filename`: The name of the generated UI CSS and JS files. Default: `bitmovinplayer-ui`
* `--outputnames.cssPrefix`: The prefix of the UI's CSS selectors. Default: `bmpui` (as defined in `_variables.scss`)
Example: `gulp build --outputnames.filename=example` generates `example.css` and `example.js` files instead of `bitmovinplayer-ui.css` and `bitmovinplayer-ui.js` files.

Add output naming customization via CLI parameters

---

CHANGELOG.md
src/html/index.html
src/scss/skin-modern/_mixins.scss
src/scss/skin-modern/_variables.scss
src/scss/skin-modern/components/_seekbar.scss
src/scss/skin-modern/components/_volumeslider.scss

The idea is to calculate all dimensions within the seekbar based on one value (bar-height).
For the position-maker multiply with `3` then there is the same space above and bottom (position center with `margin: auto`). When you would like to adjust the size more exact add / subtract an even number to it to always keep the same. (Same applies for `seek-bar-markers`) This requires to replace the background images with css styling.
@protyposis what is your opinion on this change? Shouldn't this be at least similar in all browsers on all devices?

Fix horizontal seek bar and playback position marker alignment

---

CHANGELOG.md
src/ts/timeout.ts

Fixes a bug in `Timeout` that prevented `clear()` to work from within the `callback` and improves efficiency by using `setInterval` instead of repeatedly nested `setTimeout` calls.
```ts
const timeout = new Timeout(1000, () => {
// This did not work because due to the repeated `setTimeout` approach,
// only the previous timeout that just triggered this callback was cleared and then
// a new one was immediately created, and the timeout was never stopped.
timeout.clear();
}, true);
// Worked as expected
timeout.clear();
```

Fix timeout

---

CHANGELOG.md
src/scss/skin-modern/components/_settingspanelpageopenbutton.scss

As noticed in a test for #180 this is a fix for the misplaced SettingsPanelPageOpenButton in Firefox and IE / Edge.

Fix misplaced SettingsPanelPageOpenButton in Firefox and IE / Edge

---

CHANGELOG.md
src/ts/components/seekbar.ts

Our scrubbing behavior that the playback stops while scrubbing was lost after some v3 changes.
Restore playback after user-seeking not player-seeking.
_This is no issues in the v2 branch_

Fix unintended playback starts while scrubbing on seek-bar

---

CHANGELOG.md
src/ts/components/audioqualityselectbox.ts
src/ts/components/audiotrackselectbox.ts
src/ts/components/playbackspeedselectbox.ts
src/ts/components/subtitleselectbox.ts
src/ts/components/subtitlesettings/backgroundcolorselectbox.ts
src/ts/components/subtitlesettings/backgroundopacityselectbox.ts
src/ts/components/subtitlesettings/characteredgeselectbox.ts
src/ts/components/subtitlesettings/fontcolorselectbox.ts
src/ts/components/subtitlesettings/fontfamilyselectbox.ts
src/ts/components/subtitlesettings/fontopacityselectbox.ts
src/ts/components/subtitlesettings/fontsizeselectbox.ts
src/ts/components/subtitlesettings/windowcolorselectbox.ts
src/ts/components/subtitlesettings/windowopacityselectbox.ts
src/ts/components/videoqualityselectbox.ts

Some default elements such as select boxes to style the subtitles does not have specific css selectors.
Adding css selectors where they were missing.

Adding CSS selectors for default elements

---

CHANGELOG.md
src/ts/components/volumeslider.ts
src/ts/components/volumetogglebutton.ts
src/ts/uimanager.ts
src/ts/volumecontroller.ts

Once upon a time, the `VolumeToggleButton` displayed the mute icon when the volume was turned down to `0`. `player.isMuted()` still returned `false` because it was only the volume that was turned down, but no `player.mute()` call was done. When the user then pressed the `VolumeToggleButton`, it changed the mute state to `isMuted() === true`. In the mute state the muted icon is shown, but because it was already shown for the zero volume, nothing changed in the UI and to the user it seemed as if pressing the button did not work.
Then came #94 with the aspiration to mitigate this UX issue. Since then, it considered both `muted === true` and `volume === 0` to be muted states, so no matter if the player was muted or just the volume was turned down, a click on the button while showing the muted …

[v2] Improve volume handling

---

CHANGELOG.md
src/html/index.html
src/ts/uimanager.ts

We disabled the playback speed selection per default as we implemented the `playbackSpeedSelectionEnabled` flag.
We decided to enable the speed selection per default again.

[v2] Set playbackSpeedSelectionEnabled to true per default

---

CHANGELOG.md
src/scss/skin-modern/components/_button.scss
src/ts/components/adskipbutton.ts
src/ts/components/component.ts

As we want to disable the `AdSkipButton` during the countdown we needed some mechanism to enable / disable components. (Ads UI PR #201)
This will add `disable()` / `enable()` methods and disable click events on buttons.

Add enable and disable functionality to components

---

CHANGELOG.md
src/ts/uimanager.ts

#201 added ads UI support for UI v3 but didn't consider the new ad playback event sequence from player v8. This wasn't and issue with player 8.0 with the IMA ads module (because it uses an external player for playback), but is an issue for player 8.1 and the new Bitmovin Advertising module.
* Enter ads UI on `PlayerEvent.AdStarted`
* Exit ads UI on `PlayerEvent.AdBreakFinished`
* Refresh active UI variants when exiting ads UI (when switching from ads to main content)

Improve ad variant switching

---

CHANGELOG.md
src/ts/uifactory.ts

Fixes an issue when the UI is used with IMA advertising in the player. It could happen that the UI is visible during playback of ads, even if the ads do not require an UI and/or bring their own UI:
* if the UI was loaded after the player / IMA advertising module, it was always overlaying the IMA container and thus shown during ads playback
* if the UI was underlaying the IMA container but the IMA SDK reused the player's video element instead of creating its own (as it happens in Safari on iOS), IMA only rendered its transparent UI in the container and both UIs were visible in parallel
To fix this, the UI variant switching was changed so that there is no catch-all UI variant, but the "normal" content UI is only shown for actual content and excluded for ads.
This fix only works for the …

Hide UI during playback of ads without UI requirement

---

CHANGELOG.md
src/ts/components/uicontainer.ts

Currently the `UIContainer` (which is the root `Component` of a UI structure) tracks user interaction events, i.e. mouse and touch events, on its own HTML element to determine if the UI should be shown or hidden. This only works if the `UIContainer` actually spans over the video player, which only happens if a "filling" overlay is added as a child component, e.g. the `PlaybackToggleOverlay`. Without such a "filling" overlay, the `UIContainer` does not physically cover the video frame and therefore does not capture the necessary events to show/hide the UI.
Now the problem is that with interactive ads, i.e. ads with control buttons like with the IMA SDK or VPAID in general, we cannot use such filling overlays because they would capture all input events and thus block them from the buttons …

Custom user interaction event source element

---

CHANGELOG.md
src/ts/components/adskipbutton.ts

The text of the skip button was constantly re-set to the same message, even though the button is hidden because the active ad is not skippable.
`updateSkipMessageHandler` now returns early if the active ad is not skippable.
Additionally, in player version < `v8.3.0`, `Ad.skippableAfter` was always set to `-1` if an ad was not skippable. Starting with `v8.3.0`, `Ad.skippableAfter` will not be set if an ad is not skippable. I adjusted the relevant check to support both cases.

Do not keep updating the skipMessage if the ad is not skippable

---

CHANGELOG.md
gulpfile.js
package-lock.json
package.json

Newer node versions started to fail running gulp3. This PR upgrades the build chain to gulp4 based on https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/
Issue: https://github.com/bitmovin/bitmovin-player-ui/issues/208

Upgrade to Gulp 4

---

CHANGELOG.md
src/ts/components/seekbar.ts

If the player is paused on a live stream that has a time shift window, a `Timeout` is started which periodically updates the displayed time shift offset of the seek bar. In case the player is destroyed in this state, the updater would not get stopped and would cause uncaught `PlayerAPINotAvailableError`s.
Added clearing the updater when `release` is called on the `SeekBar`.

Fix stopping time shift offset updater of SeekBar

---

CHANGELOG.md
src/html/index.html
src/html/simple.html
src/scss/skin-modern/components/_seekbar.scss
src/scss/skin-modern/components/_seekbarlabel.scss

Currently, there are two issues within the `seekbar` related to the `box-sizing` attribute.
1) `metadataLabel` in the thumbnail preview is too long
2) `playbackPositionMarker` is too big
This didn't show up during developing due to the face that we use bootstrap on our `index.html` and bootstrap applies `box-sizing: border-box` to _all_ elements.
Therefore this PR also introduces a `simple.html` page where no bootstrap is included.

Fix box-sizing for seekbar elements

---

CHANGELOG.md
src/ts/components/seekbar.ts
src/ts/components/seekbarlabel.ts
src/ts/components/volumeslider.ts
src/ts/eventdispatcher.ts
src/ts/timeout.ts

Currently, the `RateLimitedEventListener` is checking if the delta of the `lastFiredTime` to the current timestamp is greater than the rate limit and if it will delegate the event. This lead to all events during the delta period will not be received.
This leads to an issue e.g that the time in the `seekbarLabel` could be inaccurate if the user moves the mouse fast enough over the `seekbar`. (Moving during the delta period) Those events won't be delegated to the label and the time won't update. This again leads to the impression that the seeking is inaccurate 'cause the `currentTime` after seeking is different to the time seen in the `seekbarLabel`.
We came up with the solution that the last seen event need to be triggered anyway after the `rateLimit` period.
The easiest way to test this …

Improve rateLimiting handling of RateLimitedEventListener

---

CHANGELOG.md
src/ts/components/airplaytogglebutton.ts

Currently there was no event listener in place to check if AirPlay is currently active.
Add an event listener for `AirPlayChanged` event and turn on the active state of the icon.

Change the AirPlay icon into active

---

CHANGELOG.md
src/ts/components/uicontainer.ts

The problem is that when the `UIContainer` gets initialized with `hideDelay: -1` the `release` method does not check if `userInteractionEvents` or the `uiHideTimeout` is undefined or not.
Add safety checks when releasing the `UIContainer`

Fix crash within uicontainer.release

---

CHANGELOG.md
spec/components/playbacktimelabel.spec.ts
spec/helper/MockHelper.ts
src/ts/components/playbacktimelabel.ts

The upcoming player version v8.8.0 will support the `SourceConfigOption` `startTime` also for livestreams.
No initial `TimeShifted` event will be fired when a `startTime` is configured.
We need to listen to the `Playing` event to update the live-edge status indicator.

Support start time for live

---

CHANGELOG.md
spec/uimanager.spec.ts
src/ts/uimanager.ts

When an instance of an inherited player is passed to the UI our `PlayerWrapper` does not wrap all properties of the superclass correctly.
Search for `PropertyDescriptor`s also of the prototype of the passed player instance.

Add support for es6 inheritance of the player which is passed to the UI

---

CHANGELOG.md
src/ts/stringutils.ts

Currently the documentation of how to use placeholders together with number / time format is misleading.
Added some examples to point out how the format of the placeholder should look like.

Improve ad message placeholder documentation

---

CHANGELOG.md
package-lock.json
package.json
src/ts/components/adskipbutton.ts
src/ts/components/bufferingoverlay.ts
src/ts/components/button.ts
src/ts/components/castuicontainer.ts
src/ts/components/closebutton.ts
src/ts/components/container.ts
src/ts/components/errormessageoverlay.ts
src/ts/components/label.ts
src/ts/components/listbox.ts
src/ts/components/metadatalabel.ts
src/ts/components/playbacktimelabel.ts
src/ts/components/recommendationoverlay.ts
src/ts/components/settingspanel.ts
src/ts/components/settingspanelitem.ts
src/ts/components/settingspanelpagebackbutton.ts
src/ts/components/settingspanelpagenavigatorbutton.ts
src/ts/components/settingspanelpageopenbutton.ts
src/ts/components/settingstogglebutton.ts
src/ts/components/titlebar.ts
src/ts/components/togglebutton.ts
src/ts/components/uicontainer.ts
src/ts/components/volumecontrolbutton.ts

Removes all casts around `component.getConfig()` calls which used to return a base type instead of the config type of the actual component. Closes #74.
This has been bugging me since writing the very first version of this framework. Now it is finally fixed (except for a few still required type hints in `mergeConfig`) 🎈 🎉🎈🍾🎈🍸

Fix generic typing of config objects

---

CHANGELOG.md
src/ts/uimanager.ts

Fixes the ads UI still being shown after the Player was unloaded during ad playback.

Hide ads UI when unloading the Player while an ad is playing.

---

CHANGELOG.md
spec/components/uicontainer.spec.ts
spec/helper/MockHelper.ts
src/ts/components/uicontainer.ts

On iOS 13 the first touch, on the UI, does not trigger playback. This is due to the fact that `mouse` events are also fired on that touch interaction which causes problems on iOS 13.
We now ignore the `mouse` events if the UI is currently touched. _This does not change any current behaviour._
**TODO:**

Fix iOS 13 first touch input

---

CHANGELOG.md
src/ts/components/uicontainer.ts

Reverts bitmovin/bitmovin-player-ui#260
We decided to revert this as it changes behaviour in a way which was not intended.
There will be a follow-up PR which fixes the actual issue.
This version was not yet tagged or published to NPM so this should not have any impact.

Revert "[v2] Fix iOS 13 first touch input"

---

CHANGELOG.md
spec/components/uicontainer.spec.ts
spec/helper/MockHelper.ts
spec/helper/PlayerEventEmitter.ts
src/ts/components/uicontainer.ts
src/ts/uifactory.ts

In order to improve UX we decided to show the UI per default in the following states:
- Prepared
- Paused
- Finished
As the UI is visible per default now we decided to lower the default `hideDelay` value.
**This works around multiple issues:**
- First tap not starting playback on iOS 13
- UI hides if user is scrubbing longer than the `hideDelay`

Show UI in not playing states

---

src/ts/components/uicontainer.ts

After #265 we had the issue that the first touch (after the UI faced out) would trigger a `pause` which is not intended.
Another issue is that in the case of autoplay the UI does not fade out. The reason for this was that the `play` event is triggered too early from the native SDKs. 
- Add a check if the player is currently playing when the user taps the UI. And only if not playing we want to let the click through to the toggle button
- Trigger internal state update in the `playing` event as well.
**No changelog entry added as this was not yet released**
**TODO:**

Fix issues with visible UI in prepared state

---

CHANGELOG.md
src/ts/components/controlbar.ts

Touching an element within the `ControlBar` causes the UI to not disappear after the standard few seconds. Instead, it will stay visible until another manual action is performed.
This is due to the issue that on touch devices a `mouseEnter` is fired when touching an element.
Reverting this commit 6176130 without breaking the API.
This changes the behaviour of the UI that it will now hide after the configured delay even an element in the `ControlBar` is hovered (on desktop)
**TODO:**

Hide UI even if a control-bar-element is hovered

---

CHANGELOG.md
src/ts/uifactory.ts

On mobile devices the `SettingsPanel` hides automatically after the configured default delay.
This lead to the issue that a user must be fast to change settings.
Do not hide the `SettingsPanel` automatically.
_This is the same behaviour as in v2_

Do not hide `SettingsPanel` in `modernSmallScreenUI` automatically

---

src/ts/localization/i18n.ts

related to `Player localization: broke IE since `Array.from` is not supported`
- removed the misuse of `array.match` (was confused with array.matchAll)
- removed `array.from`

Fix localization in IE

---

CHANGELOG.md
package-lock.json
package.json
spec/audioutils.spec.ts
spec/components/playbacktimelabel.spec.ts
spec/components/seekbar.spec.ts
spec/components/seekbarlabel.spec.ts
spec/helper/MockHelper.ts
spec/helper/PlayerEventEmitter.ts
src/ts/components/adclickoverlay.ts
src/ts/components/playbacktimelabel.ts
src/ts/components/playbacktogglebutton.ts
src/ts/components/seekbar.ts
src/ts/components/seekbarlabel.ts
src/ts/playerutils.ts

With player `v8.19.0` the `DurationChanged` event was introduced which will be fired when a live stream turned into a VoD. In that case, the player still returns the wall-clock-timestamps for `getCurrentTime`. Therefore we need to respect the `seekableRange` to properly translate the timestamps in a user-friendly value and back.
This PR will handle the event accordingly and respects the `seekableRange` whenever needed.
- New unit tests added
- For manual testing you can use any dash vod and following network API to fake the live part.
```js
let availabilityStartTime;
const streamDuration = 210;
let switchToVod = false;
config = {
...
network: {
preprocessHttpResponse: (type, response) => {
availabilityStartTime = availabilityStartTime || Date.now() - streamDuration * 1000;
return …
```

Handle durationChanged event

---

.travis.yml
CHANGELOG.md
gulpfile.js
package-lock.json
package.json

Newer node versions started to fail running gulp3. This PR upgrades the build chain to gulp4 based on https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/ for the `support/v2.x` branch.
Mostly a cherry-pick of https://github.com/bitmovin/bitmovin-player-ui/pull/226

Update to Gulp4 for support/v2.x branch

---

CHANGELOG.md
spec/components/seekbar.spec.ts
src/ts/components/seekbar.ts
src/ts/playerutils.ts
src/ts/uimanager.ts

moved playback position calculation logic inside a method and used each time for consistency.

fix timeline ui flicking back and forth on live streams

---

CHANGELOG.md
src/scss/skin-modern/_skin-cast-receiver.scss

Added a fix for empty transparent boxes when TTML subtitles are used with Chromecast devices.

Fix TTML subtitle background on Chromecast

---

CHANGELOG.md
package-lock.json
package.json
spec/components/subtitleoverlay.spec.ts
spec/helper/MockHelper.ts
spec/vttutils.spec.ts
src/ts/components/subtitleoverlay.ts
src/ts/components/subtitlevtt.ts
src/ts/dom.ts
src/ts/vttutils.ts

Added styling of new VTT properties and regions.
VTT subtitles now have supported styling that comes from the `.vtt` file.
Reference:
- https://www.w3.org/TR/webvtt1/
- https://www.speechpad.com/captions/webvtt

Add VTT style properties and regions

---

CHANGELOG.md
src/ts/audiotrackutils.ts
src/ts/subtitleutils.ts

Moved `selectCurrentAudioTrack()` call to the end of `refreshAudioTracks`, so the selection gets updated as well
Applied same fix to the `subtitleutils`

fix selection of audiotrack in trackutils

---

CHANGELOG.md
spec/subtitleutils.spec.ts
src/ts/subtitleutils.ts

If we playback an HLS stream twice. Notice that on the second playback, CC is not rendered although it shows as enabled in the Bitmovin UI.
The current implementation of `refreshSubtitles` that is called on `SourceUnloaded` does clear/sync `listElements`. But it does not clear `selectedItem`. Doing load or unload will constantly persist this `selectedItem`, and if we have the same subtitle `identifier` between sources, it will be rendered as `selected` in the UI. 
We are now adding `clearSubtitles()` which is being run on `PlayerEvent.SourceUnloaded`, and it will clear `listElements` and `selectedItem`.

Clear selected CC/Subtitles on source unload

---

CHANGELOG.md
src/scss/skin-modern/components/_subtitleoverlay.scss
src/ts/components/subtitleoverlay.ts

Issue: TTML region subtitles were missing region class names. TTML `displayAlign = after` case styling was missing as well.
Solution: Fixed CSS configuration of the container adding the class name on subtitle region.
Added CSS case for TTML `displayAlign = after`

Fix TTML region class names

---

CHANGELOG.md
src/scss/skin-modern/components/_subtitleoverlay.scss

Fixes the height of subtitle labels.
Mainly affects multi-line subtitles that were "cut off" by the player controls:
The subtitles get offset upwards when the player controls are shown, but if the height of the subtitles is set to auto, this causes multi-line subtitles to get "cut off" (see screenshot). Setting the height of the subtitle label fixes that.

fix partial cues when controls are visible

---

CHANGELOG.md
README.md

We had a link in our `README.md` which was pointing to the old documentation.
- Replaced outdated with up to date link.
- Fixed wrong markdown links in CHANGELOG

Fix unreachable link in README

---

CHANGELOG.md
spec/components/fullscreentogglebutton.spec.ts
spec/helper/MockHelper.ts
src/ts/components/fullscreentogglebutton.ts

On our mobile SDKs `ViewMode.Fullscreen` is not always available. We have an API to check if fullscreen is available but that was not used in the `FullscreenToggleButton`.
Respect the return value of `isViewModeAvailable` for `ViewMode.Fullscreen` and hide / show the button accordingly.

Respect isViewModeAvailable in FullscreenToggleButton

---

CHANGELOG.md
spec/components/fullscreentogglebutton.spec.ts
spec/components/pictureinpicturetogglebutton.spec.ts
spec/helper/MockHelper.ts
spec/helper/PlayerEventEmitter.ts
src/ts/components/fullscreentogglebutton.ts
src/ts/components/pictureinpicturetogglebutton.ts

In our native SDKs the availability of a `ViewMode` can change after initialization of the player / UI. Therefore we introduced the `ViewModeAvailabilityChanged` event.
Listen to the new event and change the visibility accordingly.
To enable backwards compatibility there is a check added if the event is available.

React to viewModeAvailabilityChanged event

---

CHANGELOG.md
src/scss/skin-modern/_skin-smallscreen.scss

Currently when using the small-screen-ui, the title is not aligned vertically centred / middle. This is really noticeable on mobile phones where the title is closer to the buttons on the right.
As the Title bar is displayed as `flex` we just needed to align it `center` and change the `display` to `inline-flex`
| Before | After |
| -------|------|
| ![Screenshot 2020-07-09 at 16 53 44](https://user-images.githubusercontent.com/6216959/87055827-20415900-c205-11ea-8c1e-645beae0e6ac.png)|![Screenshot 2020-07-09 at 16 53 23](https://user-images.githubusercontent.com/6216959/87055855-27686700-c205-11ea-8501-ebcf1c405867.png)|

Improve title alignment in SmallScreenUI

---

README.md
package-lock.json
package.json

I have added `node-sass` as a direct dependency. This is recommended by the `gulp-sass` project.
I don't think this needs a CHANGELOG entry as it doesn't do anything to the code.

Fix `npm ci` build failure on node 14

---

src/ts/uimanager.ts

**problem:** When there are multiple `adBreaks` for the same position, default-ui and adbreak-ui will be toggled between the ads.
Since there are not `Play` or `Playing` events after the second adBreak start `playbackToggleButton` will not be updated and as a result it'll have `onState: true`.
**fix:** manually trigger `onUpdated` event if the `adBreak` requires UI.
**PS:** a better fix would be _"don't switch UI while transitioning between adBreaks for same position"_ unfortunately that is currently not possible considering that we do not have a way to figure out if we do/not have queued ads on the player. Applying that fix would require a change in the public api...

forced a state update if the adBreak requires UI

---

CHANGELOG.md
src/scss/skin-modern/components/_seekbar.scss
src/ts/components/seekbar.ts
src/ts/components/timelinemarkershandler.ts
src/ts/uiconfig.ts

Extending `timeline markers` interface to pass `imageUrl` for `timeline markers`. These images will be rendered above the marker on the seek bar.
Update the way we render `timeline markers` - for live streams we were removing and then adding markers as marker positions keep updating. This results in jittery updating in the UI - especially now that we are adding images. To avoid this, we are keeping track of elements and only update their positions when needed. This way we are able to animate marker position changes.
Example

Timeline marker image support

---

CHANGELOG.md
spec/helper/MockHelper.ts
spec/vttutils.spec.ts
src/ts/components/subtitleoverlay.ts
src/ts/dom.ts
src/ts/vttutils.ts

When there is a subtitle with `vtt` positioning information which has an absolute value for the `line` property, the size of the container was not respected.
The position is calculated based on our default line-height and the absolute `line` property. When you resize the player this value does not change and therefore it could happen that it was rendered out of the screen.
Calculating a relative value for the CSS property based on our default line number and the `vtt.line` property.
@ reviewers: You can skip e18e05f (autoformatting using IDE)

Fix subtitle positioning not respecting container size

---

CHANGELOG.md
src/ts/components/settingspanel.ts

Putting a check to prevent a race conditions causing display to be set to 'none' when the browser tab/window is inactive.
**Issue :** 
- The method 'hideHoveredSelectBoxes' is called twice(back to back), once with timeout of settings panel and then for main controls hiding. In the method, the display of panel is set to 'none' to mark select box as inactive so that it is hidden with rest of control UI and then immediately reset back to original value so that it retains the correct value next time. 
- 'requestAnimationFrame' method is used for setting it back to original value. This works fine when window/tab is active.
- But when Tab/Window is inactive when this method is executed,
- The display is set to 'none' in the first call. 
- Since some browsers(Chromium/Edge) delay/pause execution …

Fixing issue with settings panel going blank on switching tabs

---

CHANGELOG.md
src/ts/components/playbacktimelabel.ts

When a live-stream continues after stalling the live indicator within the UI stays active like we are on the live edge. 
Update live time shift state when stalling events occur.

Fix that the live indicator stays active after stalling

---

CHANGELOG.md
src/ts/components/subtitleoverlay.ts

**Description**: Captions are not displayed in IE 11/tizen 2016 when there are no regions present in WebVTT.
**Problem**: When region labels are not present for the subtitle we are removing the absolute position set to the region container using CSS `position: unset` which is not supported in IE11 and also Tizen 2016.
**Fix**: Use CSS position property `'static'` to remove the position style.

Fix subtitle display issue for IE/tizen 2016 when no regions are present

---

CHANGELOG.md
spec/components/pictureinpicturetogglebutton.spec.ts
src/ts/uimanager.ts

Fixing two build-breaking errors:
1. https://github.com/bitmovin/bitmovin-player-ui/pull/312 broke wrapping getters and setters in `uimanager.ts` and made the corresponding unit tests fail.
The reason is that since TypeScript 3.9 getters and setters are no longer enumerable properties and thus the `for...in` loop we are using does not iterate over such properties anymore.
https://github.com/bitmovin/bitmovin-player-ui/blob/f7847b64f6323a8a027cf7f998bf3c116857ace8/src/ts/uimanager.ts#L771-L776
Side note: Currently all getters/setters on the player object are actually defined as enumerable properties which means the cases that the broken unit tests are covering are currently not relevant, they might have been in the past or become in the future.
2. …

Fix CI build errors

---

CHANGELOG.md
src/ts/components/button.ts

Description: In most modern browsers (with the exception of IE), the default button type is submit this causes an issue when we embed our player in a form, on play button press the form is submitted.
Problem: button type needs to be defined, so that browser will not consider it as submit. 
Fix: Add  `'type' : 'button'` to button component

Add button type to button component

---

CHANGELOG.md
src/ts/uifactory.ts

Exporting `bitmovin.playerui.UIFactory.modernUI()` method to allow application to create and use the UIContainer for a easy customization without needing to build and deploy the player UI JS.
For example hideDelay parameter can be easily customized using below code if `bitmovin.playerui.UIFactory.modernUI()` is exported as public. So if there is no side effect of making it public, it will allow for easy customizations for some cases like below.
```
var modernUI = new bitmovin.playerui.UIFactory.modernUI();
modernUI.config.hideDelay = 5000;
var modernSmallScreenUI = new bitmovin.playerui.UIFactory.modernSmallScreenUI();
modernSmallScreenUI.config.hideDelay = 10000;
var mainUIManager = new bitmovin.playerui.UIManager(player, [{
ui: modernSmallScreenUI,
condition: (context) => {
return …
```

Export the method to create modernUI container object

---

CHANGELOG.md
src/ts/components/controlbar.ts
src/ts/uiconfig.ts
src/ts/uimanager.ts

**Issue**
Currently controls bar auto hides in hide delay seconds even if user is hovering over any of the elements like settings panel etc. There is no configuration option to disable auto hiding in this case. 
For a little background, the default behaviour was disabling auto hide when hovered but this was changed with #272 
The reason for this change was behaviour on touch devices(Android, iOS) where tapping on an element in control bar would make it stay forever until user again taps to dismiss it. But at the same time the behaviour changed for non-touch devices like Desktop causing controls to auto hide.
**Fix**
- Bring in changes removed in #272 + additionally limit the change to non-mobile devices
- Add a configuration option to allow disabling auto hiding on hover instead of making …

Configurable hide UI when hovered

---

CHANGELOG.md
src/ts/errorutils.ts

Replace "whitelist" terminology with "allowlist" in error message.
There were no "blacklist" or similar terms.

Remove blacklist/whitelist terms

---

CHANGELOG.md
spec/helper/PlayerEventEmitter.ts
spec/uimanager.spec.ts
src/ts/uimanager.ts

As the Mobile SDKs introduce a new major version that supports playlists we need to add support for this in the UI as well.
The UI doesn't know about the playlist context for now and does not update the components.
Listen to the `PlaylistTransition` event (introduced with mobile v3) which indicates that the playlist transitioned to a new source. When this event occurs we need to update the UI accordingly to display the data from the new source. 
To achieve this we reuse the `onUpdated` event of the `UIManager` which is already in place and dispatched in the UI when a `SourceLoaded` event occurs. We can't reuse the `SourceLoaded` event for this as this event got a new behaviour in v3 and is fired for each source individually.

Handle PlaylistTransition event for Mobile v3

---

CHANGELOG.md
package-lock.json
package.json
spec/focusvisibilitytracker.spec.ts
src/scss/skin-modern/_mixins.scss
src/scss/skin-modern/components/_uicontainer.scss
src/ts/components/tvnoisecanvas.ts
src/ts/focusvisibilitytracker.ts
src/ts/uimanager.ts

There are inconsistencies across browsers on different platforms regarding if a button element receives focus upon click, see [here](https://zellwk.com/blog/inconsistent-button-behavior/#summary-of-the-results).
This causes UI controls to show a focus indicator upon clicking on certain platforms, like Chrome on Android. This is unintended behavior as the focus indicator should only be visible upon interaction via keyboard.
There would be the CCS pseudo-class [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#selectively_showing_the_focus_indicator) that we could use and it applies only on elements where `:focus` applies and the focus should be indicated to the user e.g. caused by keyboard interaction [and …

Restrict focus visibility of controls to keyboard interactions

---

CHANGELOG.md
spec/components/errormessageoverlay.spec.ts
spec/errorutils.spec.ts
spec/mobilev3playerapi.spec.ts
spec/uimanager.spec.ts
src/ts/components/errormessageoverlay.ts
src/ts/errorutils.ts
src/ts/mobilev3playerapi.ts
src/ts/uimanager.ts

`PlayerEvent.Error` does not exist anymore in the Mobile SDKs V3. Instead of this `PlayerEvent.SourceError` and `PlayerEvent.PlayerError` event is introduced.
The UI does not support the new Error events in Mobile SDKs
Listen for `PlayerEvent.SourceError` and `PlayerEvent.PlayerError` along with `PlayerEvent.Error` and make sure the message is displayed correctly. Before we had mapping of error code with error message internally, but now it is not needed as the `PlayerErrorEvent` or `SourceErrorEvent` will have the message already. We have to use it directly and apply the customization config, if present.

[PW-4666] Support mobile v3 error events

---

CHANGELOG.md
spec/components/subtitleoverlay.spec.ts
spec/helper/PlayerEventEmitter.ts
src/ts/components/subtitleoverlay.ts

_Waiting until the player PR is finished before we merge this one_ 
This PR adds support for `cueUpdate` events
Changes to the UI: 
- Whenever `cueUpdate` event is triggered, we check if there is a previous cue in the `subtitleManager` that matches the id. 
- If a match is found we create a new subtitle label and replace the current one. 
- Matching by id works because `cueUpdate` events contain the same `start` and `text` properties as the `cueEnter` event, only the `html` content is different.

[PW-5093] Add handling for `cueUpdate` events

---

CHANGELOG.md
spec/vttutils.spec.ts
src/ts/vttutils.ts

When the align property of the VTT cue is set to `end` or `right`, we set the CSS `right` property to the VTT position value. This is wrong because this moves the cue to a totally different position.
I think the whole understanding of the VTT cue positioning is wrong. We think that the cues should be positioned to the VTT cue `position` offset from the `start`, `end`, `left`, or `right` side of the video container. But this is not true, the cue should be positioned to the offset in the writing direction of the VTT.
When position align is set to `end` or `right` the cue text should be present on the right side of the cue box.
When the position align is set to `start` or `left`, the cue text should be present on the left side of the cue box.
This PR fixes the cue position when the position …

[PW-4867] Fix VTT position end alignment

---

package.json

The `prepublish` script got deprecated, and does not get executed anymore when running `npm publish` on newer npm versions.
Instead, we can use `prepare`, which has the same behavior (runs on `install`, `ci`, `publish`, and more)
For reference:
- https://github.com/npm/npm/issues/10074
- https://docs.npmjs.com/cli/v7/using-npm/scripts

Replace npm `prepublish` with `prepare`

---

CHANGELOG.md
src/ts/components/playbacktimelabel.ts
src/ts/components/seekbar.ts

As you know, we have changed a bit the behavior of the `getCurrentTime` API. So now we return the seek target immediately, and we won't wait for the seeking to be complete. This created a small inconsistency in the UI since the playback time label still only gets refreshed after the Seeked event. Also, a glitch in the buffer level can be observed during the transition from Seek to Seeked: suddenly the buffer is huge and then it gets reset 👀 
**Changes:**
- update the playback time label on Seek event
- do not update the buffer level during seekings since it currently causes a glitch due to the sudden changes that happen to the buffer level during the transition

[PW-5266] Update UI for new seeking behavior

---

.gitignore
CHANGELOG.md
src/scss/skin-modern/components/_subtitleoverlay.scss

We accidentally added empty lines to Subtitles. From the following subtitle
```
00:00:00.000 --> 00:00:05.000
We are in for a ride.
```
we would get the following overlay:
this extra empty line got added because of our support for multiple subtitles cues by the following CSS rule:
```css
.bmpui-ui-subtitle-overlay .bmpui-ui-subtitle-label:nth-child(1n-1):after {
content: "\A";
white-space: pre-line;
}
```
This pseudo element should put each subtitle cue into a separate line, but when WebVTT styling is applied, the height of the pseudo element became one line instead of 0, due to `display: inline-flex`.

Fix empty lines in subtitles

---

CHANGELOG.md
src/ts/components/playbacktimelabel.ts
src/ts/components/seekbar.ts

This PR reverts the code introduced with https://github.com/bitmovin/bitmovin-player-ui/pull/398.
The behavior of `getCurrentTime` will not change after all, so there is no need to make a UI change. 
More on this here: https://github.com/bitmovin/bitdash/pull/5125.

Revert to previous seeking behavior

---

CHANGELOG.md
src/scss/skin-modern/components/_subtitleoverlay.scss

It may happen that TTML elements rendered inside of `bmpui-ui-subtitle-overlay` conflict with other style definitions on the target application resulting in broken or unexpected subtitle styling. This aims to perform some basic reset on elements nested inside of `bmpui-ui-subtitle-overlay` to try to prevent this.

[PW-5720] Reset styles on subtitle overlay content

---

CHANGELOG.md
spec/components/seekbar.spec.ts
src/ts/components/seekbar.ts

As already identified by @iktumi  on https://github.com/bitmovin/bitmovin-player-ui/pull/387, the scrubber will bounce forward and backward while seeking. 
Why:
This happens due to the smooth transition of the scrubber connected to the current time of the player.
Every time the scrubber is moved, the relevant seek information is updated with the current time, which then moves the scrubber. 
Also when the player fires the appropriate events like 'Seeked' the position will be updated, which will overwrite the newly dragged position. 
Fix:
Do not update the scrubber position if the user is currently seeking, but still allow other operations such as dragging and position updates to update the scrubber.

Fix jumping behaviour of the seekbar scrubber while still seeking

---

src/ts/components/seekbar.ts
src/ts/components/seekbarbufferlevel.ts

Problem:
`playbackPositionHandler` has a lot of repeating logic, which is cluttered and does not allow easy testing. I am separating the calculations into standalone functions to allow cleaner reading of the live and vod case handling for the playback position.

Refactor position handler 

---

CHANGELOG.md
spec/components/seekbar.spec.ts
spec/helper/MockHelper.ts
spec/helper/PlayerEventEmitter.ts
src/ts/components/seekbar.ts

Problem:
When using the scrubber on a touch device or dragging it with the mouse, there is a chance that the scrubber will bounce back to the previous position. 
This happens due to the segment request finished updating the playback location and the user is also is dragging the scrubber. Both operations happen in parallel but there is no seeking happening yet, since dragging does not start a seek operation until the user drops the seek bar.
Also it is possible that the `seeked` event fired from the player is not in sync with setting the seeking, since they are tracked in 2 different event callbacks.
Resolve:
- Keep track of the scrubbing action to not trigger a position update if there was a segment request finished. 
- Move both `seeked` handling callbacks into one callback.

[Fix] Jumping scrubber when a segment is downloaded and the scrubber is dragged

---

CHANGELOG.md

An extra release date is added during the release. This PR removes that extra release date.

Remove extra release date from changelog

---

CHANGELOG.md
src/ts/components/timelinemarkershandler.ts

When you launch a stream and destroy the player before the 'Play' event is sent out, the console will report an unhandled exception to update the markers every 1 second. This is caused due to the `configureLivePausedTimeshiftUpdater` scheduling the timeout every 1s, but we never clear this timeout if the player was destroyed.
Listen for player destroyed and clear the `pausedTimeshiftUpdater`

Fix timeshift markers causing unhandled exception timeout

---

CHANGELOG.md
spec/components/listselector.spec.ts
src/ts/components/listbox.ts
src/ts/components/listselector.ts

Problem: By default, we are using label/text as `aria-label` for list-item when Listbox is used. When complex HTML is used as a label customer wants to have an option to provide a different value for `aria-label`
Fix: provided an option to pass optional `aria-label` when  `additem` is called for adding new items to the Listbox

[PW-6220] Provide ability to override ListBox aria-labels

---

spec/components/playbacktogglebutton.spec.ts
spec/helper/MockHelper.ts

Adds unit tests for https://github.com/bitmovin/bitmovin-player-ui/pull/431
When a toggle button changes state through calling `on()` or `off()`, the `aria-label` should be updated accordingly.

Add unit tests for aria label toggle

---

CHANGELOG.md

The changelog entry for https://github.com/bitmovin/bitmovin-player-ui/pull/431 went into the section of an already released version instead of `develop`. 
To double-check, as per the `v3.33.0` tag https://github.com/bitmovin/bitmovin-player-ui/blob/v3.33.0/CHANGELOG.md it was released without the changes of said PR.

Move changelog entry to correct section

---

README.md

Travis has updated the URL for status badges, resulting in a 404 when accessing the one that is currently displayed in the readme.
Also, the branch that used to be referenced does not exist anymore - it is now `main`.
However, since `develop` is now the default branch, it makes more sense to show the build status of that one.

Fix travis CI status badge link

---

CHANGELOG.md
spec/vttutils.spec.ts
src/scss/skin-modern/components/_subtitleoverlay.scss
src/ts/vttutils.ts

Vtt cues with style
`00:00:00.000 --> 00:00:09.000 line:83%,end`
with multiple lines don't render cue box position correctly.
Such cues would use css **margin-\*** properties to apply line alignment,(*) but the method uses the cue line height in the calculation. First commits in this branch corrected this with a line count factor, but it was still not accurate. One problem is that values in pixels are only calculated at a future step (e.g. in the user agent browser).
One solution is to use relative sizes and offset proportions and compensate vtt **lineAlign** in the CSS properties that implement vtt **line** (**top**, **bottom**, **left**, **right**). This is the approach in this branch.
There remains the problem of line align "center" style which would need to calculate the cue height, …

Line align "end" not correct for multiple line cues

---

CHANGELOG.md
spec/components/playbacktimelabel.spec.ts
spec/helper/PlayerEventEmitter.ts
src/ts/components/playbacktimelabel.ts

It was found that in certain circumstances the time label would not count the hours, only the minutes and seconds that remain.
The time label has a format that is defined when it's initialized. If the player duration when it's initialized < 1 hour, this format will be _mm:ss_ so the hour quantity would always be ignored.
```
Player                                       Player UI
---------------------------------------------------------------
player not ready yet                                    |
player duration = 0                                     |
|                                 UI time label initializes
|                                 set time format, read duration
|                                  < 1 hour => time format = mm:ss   
| …
```

set time format after ready event

---

src/ts/spatialnavigation/navigationalgorithm.ts
src/ts/spatialnavigation/seekbarhandler.ts

On tested Tizen and Webos systems, the HTMLElement.`getBoundingClientRect()` returns a **ClientRect** object instead of the expected **DOMRect** object. The **ClientRect** object does NOT contain `x` and `y` properties but instead both **ClientRect** and **DOMRect** do contain `left` and `top` properties.
~~Changed navigationalgorithm.`getElementVector` to use `left` and `top`~~
~~Changed seekbarhandler.`initializeCursorPosition` to use `left` and `top`~~
Changed navigationalgorithm.`getElementVector` to use `left` and `top` in instances where `x` and `y` are not available
Changed seekbarhandler.`initializeCursorPosition` to use `left` and `top` in instances where `x` and `y` are not available

PW-8039 Fix/spatialnavigation/bounding client rect

---

spec/spatialnavigation/listnavigationgroup.spec.ts
src/ts/spatialnavigation/ListNavigationGroup.ts
src/ts/uifactory.ts

The current spatial navigation implementation did not close list/track navigation groups if the user clicked `Left` or `Right` buttons of the remote or when a list item/track was selected.
This PR therefore introduces a `ListNavigationGroup` that automatically closes the navigation group when user navigates left or right (or up and down depending on the `ListOrientation`) and when a list item was selected.

Improve track list spatial navigation

---

CHANGELOG.md
src/ts/components/component.ts
src/ts/uimanager.ts

When releasing the UI shortly after creation, there may not be a DOM element associated with the UiContainer component.
When the getter `getDomElement()` is called, the element is then created, only to be removed again right after.
This creates unnecessary operations and allocates memory.
- When destroying, check if DOM element exists before calling getter

Fix unnecessary DOM element creation on release

---

CHANGELOG.md
package-lock.json
src/ts/components/errormessageoverlay.ts

Added a `display(errorMessage: string): void` method to the `ErrorMessageOverlay` to enable its usage also for application errors without player errors while keeping the same look and feel.

Enable usage of ErrorMessageOverlay without Player Errors

---

.github/workflows/ci.yml
.github/workflows/release.yml

Reduce CI & Release workflows run time:
- CI workflow by ~30 sec by 
- storing only the built files as the artifact (thanks @offnertho for the idea)
- putting the artifact files into a tarball
- Release workflow by ~15-20 sec by
- checkout out the repo freshly instead of downloading all files as the artifact
- downloading only the built files as tarball artifact

Reduce CI build time

---

src/ts/main.ts

Add exports to `main.ts`:
- `localization/i18n.ts`
- `spatialnavigation/*`
This allows their usage in externally configured UIs

Export localization and Spatial Navigation

---

CHANGELOG.md
src/ts/components/hugeplaybacktogglebutton.ts
src/ts/components/playbacktogglebutton.ts
src/ts/components/playbacktoggleoverlay.ts
src/ts/uiconfig.ts
src/ts/uifactory.ts

Inspired by https://community.bitmovin.com/t/setting-full-screen-with-the-configuration-in-javascript/1658/6 this PR adds a configuration to `PlaybackToggleButton`, `HugePlaybackToggleButton` and `PlaybackToggleOverlay` to enter fullscreen on the first attempt to initiate playback via one of those components.
The default value is set to `false`, so no behavior is changed automatically when users update the UI.

Add configuration to enter fullscreen on initial play

---

src/ts/uifactory.ts

`main` was referencing `uifactory`, which then imported back from `main`.
Changing to remove this circular dependency

fix: remove circular dep on AudioTrackListBox

---

CHANGELOG.md
src/ts/components/subtitleoverlay.ts
src/ts/dom.ts
src/ts/uiconfig.ts

Certain constellations of VTT properties (see bottom of description for example) can cause the subtitle labels to overflow their container in the UI. Even though the UI handling in this case is spec-conform and expected, it would be convenience-feature to force such subtitles back into the respective container so they are fully visible. 
Could be helpful if users of the UI don't control the source/format of their VTT files or the results of the VTT parser.
For that matter, a config option `forceCroppedSubtitlesIntoViewContainer` is introduced with this PR. It is not `true` by default, as it breaks spec conformity by overriding certain VTT properties.
**Display with** `forceCroppedSubtitlesIntoViewContainer = false`
**Display with** `forceCroppedSubtitlesIntoViewContainer = true`
**Sample …

Force overflowing subtitles back into container

---

CHANGELOG.md
spec/helper/MockHelper.ts
spec/volumecontroller.spec.ts
src/ts/volumecontroller.ts

When we call the player API directly, such as `player.setVolume(20)` in the browser console, the volume data was not stored in UI. Thus, when trying to restore volume data, (e.g. when unmuting) the value did not get applied.
- Store volume on VolumeChanged event
- Unit test for storing the volume

Fix volume restoration when changing it via the API

---

CHANGELOG.md
src/ts/components/controlbar.ts

Problem: The settings panel requires a double touch to close when the control bar on mobile devices auto-hides (small screen UI). 
Fix: Added change to cancel the auto-hide of control bar when the settings panel is active on mobile devices. Once the user interacts with the Settings panel and closes(x) it, the auto-hide will work as usual.

Fix settings panel closing issue in the small screen UI (mobile devices)

---

CHANGELOG.md
spec/components/subtitleoverlay.spec.ts
src/ts/components/subtitleoverlay.ts

When seeking, we removed all active subtitles, even when we seeking inside the range of the active subtitle. In that case the UI would not display the Cue because the player will only fire a `CueExit` + `CueEnter` when we played outside of the Cue.
So in this PR we check the playback range of all active cues after a Seek / Timeshift operation has been completed and only remove cues which do not enclose the new current time.

Only remove subtitles which do not encompass the seek target

---

CHANGELOG.md
spec/spatialnavigation/navigationgroup.spec.ts
src/ts/spatialnavigation/navigationgroup.ts

When using the magic remote of LG TVs, which behave like a mouse we need a way to switch from the remote back to arrow button navigation. For this we
- remove the focus when the "mouse" leaves a component
- When an arrow key is pressed, we focus the last component which had focus for the navigation to continue there.

Spatial Navigation - Arrow key continues at last element

---

CHANGELOG.md
src/ts/components/seekbar.ts

When the `playbackPositionHandler` inside the `Seekbar` is called without an event (i.e., with `null`), such as during the reception of a `SourceLoaded` event, the application crashes. This leads to an undefined UI state where the `seekbar` is partially updated to the player state, and the play button may be missing.
Adding the missing `null` check for the optional event parameter.

Fix an exception when receiving a `SourceLoaded` event during scrubbing.

---

CHANGELOG.md
src/scss/skin-modern/components/_bufferingoverlay.scss
src/scss/skin-modern/components/_closebutton.scss
src/scss/skin-modern/components/_hugeplaybacktogglebutton.scss
src/scss/skin-modern/components/_hugereplaybutton.scss

CSS Animations (`@keyframe`) were not prefixed with the default `bmpui` prefix which is used for all CSS classes and names. This could lead to clashes in applications and websites that use the same name. Especially names like `fade-in` or `fade-out` have a high probability.
This PR applies the prefix also for those animations.

Prefix css animations
