bitmovin/bitmovin-player-ui

- package-lock.json
- package.json
As the title says. Looks like a smooth upgrade, no code fixes needed it seems :)
> Upgrade TypeScript to 2.4

- CHANGELOG.md
- gulpfile.js
- package-lock.json
- package.json
- src/ts/main.ts
Adds a UI version property to the global namespace (`bitmovin.playerui.version`).
> Add version property to global playerui namespace

- CHANGELOG.md
- src/ts/components/recommendationoverlay.ts
Clearing of recommendations failed due to the same problem as #29 (concurrent list iteration and modification). Discovered during testing of #34.
> Fix clearing of recommendations

- src/ts/components/playbacktimelabel.ts
Useful to extend the class, for example in custom UI
> Adds a setter for time format to playbacktimelabel

- src/ts/components/adclickoverlay.ts
- src/ts/components/hugeplaybacktogglebutton.ts
- src/ts/components/hugereplaybutton.ts
- src/ts/components/playbacktimelabel.ts
- src/ts/components/playbacktogglebutton.ts
- src/ts/components/seekbar.ts
- src/ts/components/volumeslider.ts
- src/ts/components/volumetogglebutton.ts
- src/ts/player-events.d.ts
- src/ts/player.d.ts
Should have been merged in develop not into master
> Revert "Using the new issuer parameter in Events"

- CHANGELOG.md
- src/scss/skin-legacy/_mixins.scss
- src/scss/skin-modern/_mixins.scss
Fix `animate-slide-in-from-bottom` mixin
> Fix animate-slide-in-from-bottom mixin

- CHANGELOG.md
- src/html/index.html
- src/scss/skin-modern/components/_subtitleoverlay-cea608.scss
- src/scss/skin-modern/components/_subtitleoverlay.scss
- src/ts/components/subtitleoverlay.ts
Reverts bitmovin/bitmovin-player-ui#62
Accidentally committed into master instead of development.
> Revert "CEA-608: Rewritten text layouting, CSS simplification & code improvements"

- CHANGELOG.md
- src/html/index.html
- src/scss/skin-modern/components/_subtitleoverlay-cea608.scss
- src/scss/skin-modern/components/_subtitleoverlay.scss
- src/ts/components/subtitleoverlay.ts
The "real" PR #62 was accidentally merged into `master` (then deleted by force push). This is the retry to merge the feature into `develop`.
> CEA-608: Rewritten text layouting, CSS simplification & code improvements

- CHANGELOG.md
- src/ts/player.d.ts
- src/ts/uimanager.ts
#93 was accidentally merged into `master` instead of `develop`. I removed the merge commit from `master`, and this PR correctly merges it into `develop`.
> Fix merge target of #93

- CHANGELOG.md
- src/ts/components/playbacktogglebutton.ts
> Switch play buttons to paused state when playback is rejected by browser

- CHANGELOG.md
- src/ts/components/hugeplaybacktogglebutton.ts
> Hide play button when autoplay is enabled

- CHANGELOG.md
- src/html/index.html
- src/ts/components/metadatalabel.ts
- src/ts/components/recommendationoverlay.ts
- src/ts/components/seekbar.ts
- src/ts/components/seekbarlabel.ts
- src/ts/dom.ts
- src/ts/uimanager.ts
> API to dynamically manage timeline markers

- src/ts/player-config.d.ts
adjusted AdaptationPlatformConfig to match the actual player config since 7.7.0
no seperate changelog as this is covered by 
```md
- Player type definitions updated to player v8
```
> AdaptationPlatformConfig now extends AdaptationConfig

- CHANGELOG.md
- src/ts/components/admessagelabel.ts
- src/ts/components/adskipbutton.ts
> [support-v2] Custom skip ad message not displayed

- src/ts/audiotrackutils.ts
- src/ts/components/audioqualityselectbox.ts
- src/ts/components/castuicontainer.ts
- src/ts/components/pictureinpicturetogglebutton.ts
- src/ts/components/playbackspeedselectbox.ts
- src/ts/components/playbacktimelabel.ts
- src/ts/components/recommendationoverlay.ts
- src/ts/components/seekbar.ts
- src/ts/components/seekbarlabel.ts
- src/ts/components/uicontainer.ts
- src/ts/components/videoqualityselectbox.ts
- src/ts/components/volumeslider.ts
- src/ts/components/vrtogglebutton.ts
- src/ts/playerutils.ts
- src/ts/subtitleutils.ts
- src/ts/uimanager.ts
Referencing [this comment](
https://github.com/bitmovin/bitmovin-player-ui/pull/144#discussion_r211604063) i replaced event listeners on `ready` with listeners for `sourceLoaded`.
> On ready component initialization

- CHANGELOG.md
- src/ts/components/subtitleoverlay.ts
- src/ts/player-events.d.ts
> Cherry pick for image attribute on cue-enter event

- CHANGELOG.md
- package.json
- src/ts/main.ts
Implements #152 and fixes #104
> ES6 exports and fix type definitions

- CHANGELOG.md
- src/scss/skin-modern/components/_bufferingoverlay.scss
- src/ts/components/label.ts
* Don't animate the `BufferingOverlay` while it's hidden (see commit for explanation)
* Don't modify DOM when a `Label`'s text isn't changing
> Performance optimizations

- CHANGELOG.md
- src/scss/skin-modern/components/_bufferingoverlay.scss
- src/ts/components/label.ts
> [2.x] Performance optimizations

- CHANGELOG.md
- src/ts/components/selectbox.ts
> IE not turning off subtitles

- package-lock.json
- package.json
Fixes the page reloading on debugger breakpoint issue.
> Update BrowserSync to 2.26.3

- CHANGELOG.md
- src/ts/components/volumeslider.ts
- src/ts/components/volumetogglebutton.ts
- src/ts/uimanager.ts
- src/ts/volumecontroller.ts
> Improve volume handling

- CHANGELOG.md
- src/scss/skin-modern/_skin-ads.scss
- src/ts/components/adclickoverlay.ts
- src/ts/components/admessagelabel.ts
- src/ts/components/adskipbutton.ts
- src/ts/demofactory.ts
- src/ts/uifactory.ts
- src/ts/uimanager.ts
Up to now we do not have support for Ads in the UI as it's not part in player v8.0.
As this is getting added in player v8.1 we need to add UI support for ads as well.
Add Ads UI support.
_Builds will fail until upgrading to player 8.1_
> Ads UI support for player v8

- CHANGELOG.md
- src/ts/components/audioqualityselectbox.ts
- src/ts/components/videoqualityselectbox.ts
> Add events to update quality select boxes

- src/html/index.html
Updates all functionality in the test page to v8 API:
* Enumerate module namespace methods
* Sort API methods and events a-z
* Update ads test actions
* Update subtitle test actions
* Update resize test action
* Add source reload test action
* Decrease ad schedulting delay from 5 to 2 seconds
* Add native video element event logging
> Update test page

- README.md
Fixed a few grammar mistakes and removed some of the unnecessary words.
> Tidied up README.md a bit

- CHANGELOG.md
- spec/browserutils.spec.ts
- src/ts/browserutils.ts
Our `BrowserUtils` check against the `userAgent` without checking if we are in a browser environment and if the `navigator` object even exists. This lead to issues e.g. when rendering server side.
Check the user agent when it's needed and add a check if the window object is defined.
Simple test for `isMobile` added
> Fix issues if the UI is used in a non browser environment

- CHANGELOG.md
- spec/components/playbacktimelabel.spec.ts
- spec/helper/MockHelper.ts
- src/ts/components/playbacktimelabel.ts
This PR will add a new `PlaybackTimeLabelMode` option to display the remaining time in the `PlaybackTimeLabel`.
- new tests for PlaybackTimeLabelMode added
> Add RemainingTime option for PlaybackTimeLabelMode

- CHANGELOG.md
- spec/components/settingspanel.spec.ts
- spec/helper/MockHelper.ts
- src/scss/skin-modern/_skin-smallscreen.scss
- src/scss/skin-modern/components/_listbox.scss
- src/scss/skin-modern/components/_settingspanelpage.scss
- src/ts/components/playbacktogglebutton.ts
- src/ts/components/seekbar.ts
- src/ts/components/settingspanel.ts
- src/ts/components/settingspanelpagenavigatorbutton.ts
- src/ts/components/subtitlesettings/subtitlesettingslabel.ts
- src/ts/stringutils.ts
- src/ts/uifactory.ts
- tslint.json
**Issue: #224**
_This PR actually solves two issues_
1) The calculation of the size of the `SettingsPanel` which is needed for the animation between `SettingPanelPages` lead to the issue that the `SettingsPanel` expands unexpectedly in certain cases.
2) If you have more than two pages the navigation was not working correctly as we were stuck in the penultimate page and were not able to navigate further back.
1) The size calculation was rewritten and now only considers the size of the target `SettingsPanelPage`.
2) Don't push pages to the stack if we are navigating back.
_Since we don't have UI tests (yet) the actual issue is not covered with tests_
- A simple test for navigation between pages was added.
- To test the root issue you can select `UIWithSeparateAudioSubtitlesButtons` from the …
> Improve SettingsPanelPage animation

- CHANGELOG.md
- src/ts/components/uicontainer.ts
> [v2] Fix iOS 13 first touch input

- CHANGELOG.md
- spec/components/uicontainer.spec.ts
- spec/helper/MockHelper.ts
- src/ts/components/uicontainer.ts
This was accidentally merged into `master` instead of `dev`
> Revert 259 feature/fix ios 13 first touch

- CHANGELOG.md
- spec/components/seekbarlabel.spec.ts
- spec/helper/MockHelper.ts
- src/ts/components/seekbarlabel.ts
With the upcoming player release, the player supports thumbnail preview for live streams.
This PR makes use of this new feature in a way that it requests the Thumbnail for the seek preview target.
> Thumbnail preview for live

- src/ts/components/uicontainer.ts
> [v2] Fix issues with visible UI in prepared state

- CHANGELOG.md
- spec/components/subtitleoverlay.spec.ts
- spec/helper/PlayerEventEmitter.ts
- src/scss/skin-modern/components/_subtitleoverlay-cea608.scss
- src/scss/skin-modern/components/_subtitleoverlay.scss
- src/scss/skin-modern/components/subtitlesettings/_subtitleoverlay-settings.scss
- src/ts/components/subtitleoverlay.ts
Allow for different regions and use a `default-subtitle` style for other cases.
> TTML multi region

- CHANGELOG.md
- src/ts/components/controlbar.ts
> [v2] Hide UI even if a control-bar-element is hovered

- CHANGELOG.md
- gulpfile.js
fixed missing file reference error by adding a build step (`copy-json`) in order to copy json files in the production build. 
related to #279
> UI localization not building when importing npm

- CHANGELOG.md
- src/html/index.html
The live asset which is currently included is outdated.
Update the live asset.
> Fix live asset

- CHANGELOG.md
- src/ts/components/seekbar.ts
- src/ts/components/uicontainer.ts
Fixed UI hiding while seeking or changing volume.
Holding and dragging the sliders to change values won't make the UI hide anymore.
> Fix UI hiding while seeking or changing volume

- CHANGELOG.md
- spec/vttutils.spec.ts
- src/ts/vttutils.ts
Fixed future regression with VTT position alignment
> Fix VTT position alignment

- CHANGELOG.md
- package-lock.json
- package.json
- src/scss/skin-modern/components/_subtitleoverlay.scss
> [RELEASE] v3.13.0

- CHANGELOG.md
- src/html/index.html
- src/ts/components/seekbar.ts
- src/ts/uiconfig.ts
Co-authored-by: Stefan Krainer <stefan.krainer@bitmovin.com>
> Make seekbar snapping range configurable

- CHANGELOG.md
- package-lock.json
- package.json
> Update Typescript to 3.9.6

- CHANGELOG.md
Added missing changelog for the https://github.com/bitmovin/bitmovin-player-ui/pull/316
> Added changelog for pull#316

- CHANGELOG.md
- package-lock.json
- package.json
> [RELEASE] v3.19.0

- CHANGELOG.md
- package-lock.json
- package.json
> [RELEASE] v3.23.0

- CHANGELOG.md
- src/ts/components/seekbar.ts
Fixed the 'Touchscreen is undefined' error on IE/UWP when using mouse and touchscreen laptop
> PW-4775 touchscreen error IE/UWP fix

- CHANGELOG.md
- package-lock.json
- package.json
> [RELEASE] v3.26.0

- CHANGELOG.md
- spec/components/subtitleoverlay.spec.ts
- spec/helper/PlayerEventEmitter.ts
- src/ts/components/subtitleoverlay.ts
Reverts bitmovin/bitmovin-player-ui#378's merge into `master` as it should have gone into `develop`
> Revert "[PW-5093] Add handling for `cueUpdate` events"

- CHANGELOG.md
- spec/components/subtitleoverlay.spec.ts
- spec/helper/PlayerEventEmitter.ts
- src/ts/components/subtitleoverlay.ts
PR for basically merging the PR https://github.com/bitmovin/bitmovin-player-ui/pull/378 into `develop` -- it had to be reverted as it went straight into `master`.
For more info on the changes refer to the original PR.
> Add handling for `CueUpdate` events

- CHANGELOG.md
- package-lock.json
- package.json
> [RELEASE] v3.28.1

- CHANGELOG.md
- package-lock.json
- package.json
Merge release branch into `develop` after starting release `v3.32.0`
> [RELEASE START] v3.32.0 > develop

- CHANGELOG.md
- src/ts/components/seekbar.ts
Merge back into `develop` after release `v3.32.0`
> [RELEASE FINISH] v3.32.0 > develop

- CHANGELOG.md
- package-lock.json
- package.json
Merge release branch into `develop` after starting release `v3.33.0`
> [RELEASE START] v3.33.0 > develop

- CHANGELOG.md
- src/ts/components/seekbar.ts
Merge back into `develop` after release `v3.33.0`
> [RELEASE FINISH] v3.33.0 > develop

- CHANGELOG.md
- src/ts/components/playbacktogglebutton.ts
- src/ts/localization/languages/de.json
- src/ts/localization/languages/en.json
Problem: The `aria-label` is not updated when the playback button is toggled.
Fix: Added change to update the aria-label on playback button toggle
> [PW-6221]Added change to update aria-label on playbackbutton toggle

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.35.0`
> [RELEASE START] v3.35.0 > develop

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.36.0`
> [RELEASE START] v3.36.0 > develop

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.37.0`
> [RELEASE START] v3.37.0 > develop

- CHANGELOG.md
- package-lock.json
Merge back into `develop` after release `v3.37.0`
> [RELEASE FINISH] v3.37.0 > develop

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.38.0`
> [RELEASE START] v3.38.0 > develop

- CHANGELOG.md
- assets/skin-modern/images/replay-nocircle.svg
- src/scss/skin-modern/_skin.scss
- src/scss/skin-modern/components/_replaybutton.scss
- src/ts/components/replaybutton.ts
- src/ts/main.ts
Add new ReplayButton component that can be used in controlbar and works during playback
> Add new ReplayButton component

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.39.0`
> [RELEASE START] v3.39.0 > develop

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.40.0`
> [RELEASE START] v3.40.0 > develop

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.41.0`
> [RELEASE START] v3.41.0 > develop

- CHANGELOG.md
- package-lock.json
- package.json
Merge release branch into `develop` after starting release `v3.42.0`
> [RELEASE START] v3.42.0 > develop

- CHANGELOG.md
- package.json
> [RELEASE] v3.43.0

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.43.0`
> [RELEASE START] v3.43.0 > develop

- CHANGELOG.md
- package-lock.json
- package.json
Merge release branch into `develop` after starting release `v3.44.0`
> [RELEASE START] v3.44.0 > develop

- CHANGELOG.md
- package-lock.json
- package.json
> [RELEASE] v3.44.0

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.45.0`
> [RELEASE START] v3.45.0 > develop

- CHANGELOG.md
Merge back into `develop` after release `v3.45.0`
> [RELEASE FINISH] v3.45.0 > develop

- CHANGELOG.md
- package-lock.json
- package.json
Merge release branch into `develop` after starting release `v3.46.0`
> [RELEASE START] v3.46.0 > develop

- CHANGELOG.md
I accidentally merged my branch after automatically merging dev into it, leaving the changelog entry in the wrong section.
> [Fix] Move changelog entry to dev

- CHANGELOG.md
- package-lock.json
- package.json
Merge release branch into `develop` after starting release `v3.47.0`
> [RELEASE START] v3.47.0 > develop

- spec/spatialnavigation/spatialnavigation.spec.ts
- spec/uimanager.spec.ts
- src/ts/spatialnavigation/spatialnavigation.ts
- src/ts/uimanager.ts
When multiple UIs are used with the UI manager and each one has a spatial navigation configured, you can select a button with the arrow keys and a press on `enter` would call all `onclick` handlers of all UIs, even if they are not active.
After a UI has changed there would even be an error in the console:
```error
bitmovinplayer-ui.js:11 Uncaught TypeError: Cannot read properties of undefined (reading 'handleAction')
at HTMLDocument.handleKeyEvent (bitmovinplayer-ui.js:11:235800)
```
because the `getActiveNavigationGroup` will return `null` [here](https://github.com/bitmovin/bitmovin-player-ui/blob/88b4336a3c0369bf362e5126180ceee2292e9bf6/src/ts/spatialnavigation/spatialnavigation.ts#L131).
This PR now changes the behavior:
- When there is no `activeNavigationGroup` or when it's hidden or …
> Multi UI spatial navigation

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.48.0`
> [RELEASE START] v3.48.0 > develop

- CHANGELOG.md
> [RELEASE FINISH] Merge pull request #554 from bitmovin/release/v3.48.0

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.50.0`
> [RELEASE START] v3.50.0 > develop

- CHANGELOG.md
Merge back into `develop` after release `v3.50.0`
> [RELEASE FINISH] v3.50.0 > develop

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.51.0`
> [RELEASE START] v3.51.0 > develop

- CHANGELOG.md
- package-lock.json
- package.json
- spec/components/subtitleoverlay.spec.ts
- src/ts/components/subtitleoverlay.ts
Reverts bitmovin/bitmovin-player-ui#574
Accidently merged it - should get merged by the release CLI though. So reverting and reopening it.
> Revert "[RELEASE] v3.51.0"

- CHANGELOG.md
- package-lock.json
- package.json
- spec/components/subtitleoverlay.spec.ts
- src/ts/components/subtitleoverlay.ts
Release `v3.51.0`
"Reverting the revert" after accidental merge. This PR should get picked up and merged by the CLI.
> [RELEASE] v3.51.0

- CHANGELOG.md
- package.json
Merge release branch into `develop` after starting release `v3.52.0`
> [RELEASE START] v3.52.0 > develop

- CHANGELOG.md
Merge back into `develop` after release `v3.52.0`
> [RELEASE FINISH] v3.52.0 > develop

- CHANGELOG.md
- package.json
> [RELEASE] v3.52.1
